### ISSUE TITLE
[Issue]: musl does not define _SC_LEVEL1_DCACHE_SIZE

### ISSUE THREAD

**Issue by omcaif** [ROCm/ROCR-Runtime#318]
### Problem Description

Failed to compile because of use of `_SC_LEVEL1_DCACHE_SIZE`

### Operating System

Gentoo Musl

### CPU

N/A

### GPU

N/A

### ROCm Version

6.4.1

### ROCm Component

ROCR-Runtime

### Steps to Reproduce

Try to compile on a musl system and encounter this error
```
In file included from /var/tmp/portage/dev-libs/rocr-runtime-6.4.1/work/ROCR-Runtime-rocm-6.4.1/runtime/hsa-runtime/core/inc/memory_region.h:52,
                 from /var/tmp/portage/dev-libs/rocr-runtime-6.4.1/work/ROCR-Runtime-rocm-6.4.1/runtime/hsa-runtime/core/inc/driver.h:49,
                 from /var/tmp/portage/dev-libs/rocr-runtime-6.4.1/work/ROCR-Runtime-rocm-6.4.1/runtime/hsa-runtime/core/inc/amd_kfd_driver.h:51,
                 from /var/tmp/portage/dev-libs/rocr-runtime-6.4.1/work/ROCR-Runtime-rocm-6.4.1/runtime/hsa-runtime/core/driver/kfd/amd_kfd_driver.cpp:43:
/var/tmp/portage/dev-libs/rocr-runtime-6.4.1/work/ROCR-Runtime-rocm-6.4.1/runtime/hsa-runtime/core/util/utils.h: In function 'void rocr::FlushCpuCache(const void*, size_t, size_t)':
/var/tmp/portage/dev-libs/rocr-runtime-6.4.1/work/ROCR-Runtime-rocm-6.4.1/runtime/hsa-runtime/core/util/utils.h:360:23: error: '_SC_LEVEL1_DCACHE_LINESIZE' was not declared in this scope
  360 |     long sz = sysconf(_SC_LEVEL1_DCACHE_LINESIZE);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ppanchad-amd** [comment]
Hi @omcaif. Internal ticket has been created to investigate this issue. Thanks!

**Comment by zichguan-amd** [comment]
Hi @omcaif, this seems to be a known issue with musl not having `_SC_LEVEL1_DCACHE_LINESIZE`. I'll draft a PR to bypass it if it's not defined.

**Comment by zichguan-amd** [comment]
Hi @omcaif, the fix has been merged into staging, you can add it as a patch to ebuild to compile it now. 

Put the following patch to `/var/db/repos/gentoo/dev-libs/rocr-runtime/files` and modify `rocr-runtime-6.4.1.ebuild` in `/var/db/repos/gentoo/dev-libs/rocr-runtime/` to include the patch. `ebuild rocr-runtime-6.4.1.ebuild manifest` to recreate the manifest, then build with `emerge rocr-runtime-6.4.1.ebuild`


```
--- a/core/util/utils.h
+++ b/core/util/utils.h
@@ -357,7 +357,11 @@
   static long cacheline_size = 0;
 
   if (!cacheline_size) {
+#ifdef _SC_LEVEL1_DCACHE_LINESIZE
     long sz = sysconf(_SC_LEVEL1_DCACHE_LINESIZE);
+#else
+    long sz = 0;
+#endif
     if (sz <= 0) return;
     cacheline_size = sz;
   }
```

**Comment by omcaif** [comment]
Hi @zichguan-amd , thanks for the patch.

For future reference, there is no need to modify the ebuild or put the patch in the gentoo repository. User patches can be placed in `/etc/portage/patches`. It can be placed in either a general directory for all versions of a package (like `/etc/portage/patches/dev-libs/rocr-runtime`), or for a specific version (like `/etc/portage/patches/dev-libs/rocr-runtime-6.4.1`).

**Comment by zichguan-amd** [comment]
Thanks for pointing that out, I'm not too familiar with portage. Hope it helped. You might want to modify the path `a/core/util/utils.h` accordingly then.
